apiVersion: apps/v1
kind: Deployment

metadata:
  name: berrystreet-deploy

spec:
  replicas: 1

  selector:
    matchLabels:
      app: berrystreet

  template:
    metadata:
      labels:
        app: berrystreet

    spec:
      containers:
      - name: berrystreet-container
        # image: berrystreet-api
        image: berrystreetacr.azurecr.io/berrystreet-api:latest
        # imagePullPolicy: Never
        ports:
        - containerPort: 8000